### ISSUE TITLE
find executable files

### ISSUE THREAD

**Issue by Konfekt** [cirosantilli/dotfiles#2]
In https://github.com/cirosantilli/dotfiles/blob/750aa4e4ad8280a960bd0f0fe883921af5770068/home/.bashrc#L300C4-L300C65
would you mind explaining how `-perm /u=x` differs from `-executable` ?

**Comment by cirosantilli** [comment]
`-executable` docs says:

> Matches  files  which  are  executable  and directories which are searchable (in a file name resolution sense) by the current user.

which does not sound like what I want for that command, rather what I want is "if any x bit is set, then set all x bits", which is what `-perm /u=x,g=x,o=x ` does.

**Comment by Konfekt** [comment]
Yes, thank you, -executable asks only for user permissions, but is `-perm /u=x` the same? Rather not, because the user executable flag is removed before being restored. So why in this order and how do they differ?

**Comment by cirosantilli** [comment]
> because the user executable flag is removed before being restored

Where is the executable flag being removed?

**Comment by Konfekt** [comment]
I misread, it is `+644` in the line before, and not `644`.  Now the question remains what `chmod +111` changes for files satisfying `-perm /u=x,g=x,o=x`. An impressive `.bashrc`, by the way.

**Comment by cirosantilli** [comment]
More like a mega dump, but thanks xd

**Comment by Konfekt** [comment]
By the law of large numbers, there ought to be many nuggets indeed.
